cloudforet-io/plugin-aws-cloud-service-inven-collector

src/spaceone/inventory/connector/aws_ec2_connector/connector.py
fix: modify tags for EC2.AMI
AMI Tags is not collected (#2)
=> fix: modify tags for EC2.AMI

src/spaceone/inventory/libs/connector.py
feat: add external_id for assume role
Add External ID for Assume Role (#4)
=> feat: add external_id for assume role

src/spaceone/inventory/connector/aws_ebs_connector/schema/resource.py
Remove tag metadata for EBS Volume.
The console display for Tag is merged into the "Tags" tab. 
* https://github.com/cloudforet-io/plugin-aws-cloud-service-inven-collector/issues/7
=> refactor: remove Tag tab (#7)

src/spaceone/inventory/connector/aws_eks_connector/schema/resource.py, src/spaceone/inventory/connector/aws_iam_connector/connector.py, src/spaceone/inventory/connector/aws_iam_connector/schema/data.py, src/spaceone/inventory/connector/aws_iam_connector/schema/resource.py, src/spaceone/inventory/connector/aws_iam_connector/schema/service_type.py, src/spaceone/inventory/libs/connector.py
Separate the `IAM.Access Key` resource in the existing `IAM.User` cloud service.
* https://github.com/cloudforet-io/plugin-aws-cloud-service-inven-collector/issues/12
=> Add AccessKey cloud service

README.md, RELEASE.md
update README.md 
add RELEASE.md
=> Update README.md RELEASE.md

src/spaceone/inventory/connector/aws_cloud_trail_connector/schema/service_type.py
chore: update cloud trail icon path
* https://github.com/cloudforet-io/plugin-aws-cloud-service-inven-collector/issues/23
=> Update cloud trail icon path

src/spaceone/inventory/connector/aws_iam_connector/schema/service_type.py
Modify metadata for IAM User for column sorting.
For sorting, modify column data with value stored in integer format, and use `postfix` as `options` value.
* https://github.com/cloudforet-io/plugin-aws-cloud-service-inven-collector/issues/18
=> Modify metadata for IAM User for column sorting

src/spaceone/inventory/connector/aws_iam_connector/schema/service_type.py
=> chore: remove blank

src/spaceone/inventory/connector/aws_iam_connector/schema/service_type.py
purpose: update postfix in metadata. for display considerations.
* https://github.com/cloudforet-io/plugin-aws-cloud-service-inven-collector/issues/18
=> Update postfix in metadata

src/spaceone/inventory/connector/aws_iam_connector/schema/service_type.py
chore: update postfix word in metadata
* https://github.com/cloudforet-io/plugin-aws-cloud-service-inven-collector/issues/18
=> Update postfix word in metadata

Dockerfile
Update Dockerfile (remove pkg upgrade)
=> Update Dockerfile (remove pkg upgrade)

Dockerfile, src/spaceone/inventory/conf/cloud_service_conf.py, src/spaceone/inventory/service/collector_service.py
Update Dockerfile to python:3.8-slim
=> Update Dockerfile to python:3.8-slim

src/spaceone/inventory/conf/cloud_service_conf.py, src/spaceone/inventory/connector/aws_auto_scaling_connector/connector.py, src/spaceone/inventory/connector/aws_cloud_trail_connector/connector.py, src/spaceone/inventory/connector/aws_dynamodb_connector/connector.py, src/spaceone/inventory/connector/aws_eks_connector/connector.py, src/spaceone/inventory/connector/aws_elb_connector/connector.py, src/spaceone/inventory/connector/aws_s3_connector/connector.py, src/spaceone/inventory/connector/aws_sns_connector/connector.py, src/spaceone/inventory/connector/aws_sqs_connector/connector.py, src/spaceone/inventory/libs/connector.py
Modify collecting CloudTrail logic
=> Modify collecting CloudTrail logic

src/spaceone/inventory/connector/aws_cloud_trail_connector/connector.py, src/spaceone/inventory/service/collector_service.py
=> Except collecting a tags

README.md, RELEASE.md, docs/ko/GUIDE.md
- update github link from spaceone-dev to cloudforet-io
The link to connect to GitHub issues in RELEASE.md does not work because the issues do not exist.
=> doc: update link in markdown files

README.md, RELEASE.md
Update README.md and RELEASE.md
=> Update README.md and RELEASE.md

src/spaceone/inventory/connector/aws_s3_connector/connector.py, test/api/test_cloudservice_api.py
Remove logger which not found error
=> Remove logger which not found error

src/spaceone/inventory/connector/aws_s3_connector/connector.py
Modify time sleep time 0.3 to 0.1
=> Modify time sleep time 0.3 to 0.1

src/spaceone/inventory/connector/aws_elasticache_connector/connector.py
Add try except blocks for list tags (elasticache)
=> Add try except blocks for list tags (elasticache)

src/spaceone/inventory/connector/aws_elasticache_connector/schema/service_type.py
Add cache status display metadata
=> Add cache status display metadata

src/spaceone/inventory/conf/cloud_service_conf.py
* Change BOTO3_HTTPS_VERIFIED from True to None in cloud_service_conf
=> Change BOTO3_HTTPS_VERIFIED from True to None in cloud_service_conf

src/spaceone/inventory/connector/aws_rds_connector/schema/service_type.py, src/spaceone/inventory/connector/aws_vpc_connector/connector.py
Modify filter for describe vpc peering connection
=> Modify filter for describe vpc peering connection

src/spaceone/inventory/connector/aws_acm_connector/connector.py, src/spaceone/inventory/connector/aws_api_gateway_connector/connector.py, src/spaceone/inventory/connector/aws_auto_scaling_connector/connector.py, src/spaceone/inventory/connector/aws_direct_connect_connector/connector.py, src/spaceone/inventory/connector/aws_documentdb_connector/connector.py, src/spaceone/inventory/connector/aws_dynamodb_connector/connector.py, src/spaceone/inventory/connector/aws_ebs_connector/connector.py, src/spaceone/inventory/connector/aws_ec2_connector/connector.py, src/spaceone/inventory/connector/aws_ecr_connector/connector.py, src/spaceone/inventory/connector/aws_ecs_connector/connector.py, src/spaceone/inventory/connector/aws_efs_connector/connector.py, src/spaceone/inventory/connector/aws_eip_connector/connector.py, src/spaceone/inventory/connector/aws_eks_connector/connector.py, src/spaceone/inventory/connector/aws_elasticache_connector/connector.py, src/spaceone/inventory/connector/aws_elb_connector/connector.py, src/spaceone/inventory/connector/aws_kinesis_data_stream_connector/connector.py, src/spaceone/inventory/connector/aws_kinesis_firehose_connector/connector.py, src/spaceone/inventory/connector/aws_kms_connector/connector.py, src/spaceone/inventory/connector/aws_lambda_connector/connector.py, src/spaceone/inventory/connector/aws_lightsail_connector/connector.py, src/spaceone/inventory/connector/aws_msk_connector/connector.py, src/spaceone/inventory/connector/aws_redshift_connector/connector.py, src/spaceone/inventory/connector/aws_secrets_manager_connector/connector.py, src/spaceone/inventory/connector/aws_sns_connector/connector.py, src/spaceone/inventory/connector/aws_sqs_connector/connector.py, src/spaceone/inventory/connector/aws_vpc_connector/connector.py, src/spaceone/inventory/libs/connector.py, src/spaceone/inventory/service/collector_service.py, test/api/test_cloudservice_api.py
Add try/exception for loop regions
=> Add try/exception for loop regions

src/setup.py
=> fix: changed some unexpected typos

src/spaceone/inventory/service/collector_service.py
=> fix: changed code to match with updated version of spaceone core

src/spaceone/inventory/connector/aws_vpc_connector/connector.py, src/spaceone/inventory/connector/aws_vpc_connector/schema/data.py, src/spaceone/inventory/connector/aws_vpc_connector/schema/resource.py, src/spaceone/inventory/connector/aws_vpc_connector/schema/service_type.py
Currently, we only show one CIDR block range for each VPC. This turned out to be incomplete as there could be more than one CIDR associated with each VPC. So, I made an attempt to show all CIDRs related to each VPC.
=> Changed code to show all CIDR blocks associated with VPC

src/spaceone/inventory/connector/aws_vpc_connector/schema/resource.py
=> Changed item dynamic field key to match model specification

src/spaceone/inventory/connector/aws_vpc_connector/schema/resource.py
=> Changed item dynamic field key layout for testing design

src/spaceone/inventory/connector/aws_iam_connector/connector.py, src/spaceone/inventory/connector/aws_vpc_connector/schema/resource.py
=> Removed dictionary format typo on IAM connector and changed display format of VPC CIDR blocks

src/spaceone/inventory/connector/aws_cloud_trail_connector/connector.py, src/spaceone/inventory/connector/aws_documentdb_connector/connector.py, src/spaceone/inventory/connector/aws_documentdb_connector/schema/resource.py, src/spaceone/inventory/interface/grpc/collector.py, src/spaceone/inventory/libs/connector.py, test/api/test_cloudservice_api.py
=> Fixed TrailNotFound Error for CloudTrail

src/spaceone/inventory/connector/aws_lightsail_connector/connector.py, src/spaceone/inventory/service/collector_service.py, test/api/test_cloudservice_api.py
=> Added additional region filter for lightsail to fix endpoint error

src/spaceone/inventory/conf/cloud_service_conf.py, src/spaceone/inventory/connector/__init__.py, src/spaceone/inventory/connector/aws_ebs_connector/schema/widget/snapshot_total_size_by_region.yaml, src/spaceone/inventory/connector/aws_ec2_connector/schema/service_type.py, src/spaceone/inventory/connector/aws_s3_connector/connector.py, src/spaceone/inventory/connector/aws_s3_connector/schema/data.py, src/spaceone/inventory/connector/aws_s3_connector/schema/service_type.py, src/spaceone/inventory/manager/__init__.py, test/api/test_cloudservice_api.py
=> Opt out ec2 resources for stg testing purposes

src/spaceone/inventory/conf/cloud_service_conf.py, src/spaceone/inventory/connector/__init__.py, src/spaceone/inventory/connector/aws_cloud_front_connector/schema/data.py, src/spaceone/inventory/connector/aws_cloud_front_connector/schema/service_type.py, src/spaceone/inventory/connector/aws_ebs_connector/schema/widget/snapshot_total_count_by_region.yaml, src/spaceone/inventory/connector/aws_ec2_connector/connector.py, src/spaceone/inventory/connector/aws_elb_connector/schema/service_type.py, src/spaceone/inventory/connector/aws_s3_connector/connector.py, src/spaceone/inventory/connector/aws_s3_connector/schema/data.py, src/spaceone/inventory/connector/aws_s3_connector/schema/resource.py, src/spaceone/inventory/connector/aws_s3_connector/schema/service_type.py, src/spaceone/inventory/libs/schema/dynamic_field.py, src/spaceone/inventory/manager/__init__.py, src/spaceone/inventory/service/collector_service.py, test/api/test_cloudservice_api.py
=> Made changes to ELB, CloudFront, and S3

src/spaceone/inventory/connector/aws_auto_scaling_connector/connector.py, src/spaceone/inventory/connector/aws_s3_connector/connector.py, src/spaceone/inventory/connector/aws_s3_connector/schema/data.py, src/spaceone/inventory/connector/aws_s3_connector/schema/resource.py
=> Changed s3 bucket permissions display format to be more human-readable

src/spaceone/inventory/connector/aws_cloud_front_connector/schema/service_type.py, src/spaceone/inventory/connector/aws_s3_connector/schema/resource.py
=> Improved on some parts for CloudFront and S3

src/spaceone/inventory/connector/aws_elb_connector/schema/service_type.py
=> Added security policy to show up on main table for elb

src/spaceone/inventory/conf/cloud_service_conf.py, src/spaceone/inventory/conf/global_conf.py, src/spaceone/inventory/connector/__init__.py, src/spaceone/inventory/connector/aws_api_gateway_connector/connector.py, src/spaceone/inventory/connector/aws_elb_connector/connector.py, src/spaceone/inventory/connector/aws_elb_connector/schema/data.py, src/spaceone/inventory/manager/__init__.py
…ata for custom metrics.
Check available region to use apigatewayv2 api. And add stats data for custom metrics.
=> Check available region to use apigatewayv2 api. And add stats data for custom metrics.

src/spaceone/inventory/connector/aws_cloud_trail_connector/schema/service_type.py
fix: Change CloudTrail labels to "Security".
=> Change CloudTrail labels to "Security".

src/spaceone/inventory/conf/cloud_service_conf.py, src/spaceone/inventory/connector/__init__.py, src/spaceone/inventory/manager/__init__.py
Rollback: enabeld collect ec2 cloud_service_group.
=> Rollback: enabeld collect ec2 cloud_service_group.

src/spaceone/inventory/conf/cloud_service_conf.py, src/spaceone/inventory/connector/__init__.py, src/spaceone/inventory/manager/__init__.py
feat: Move to collector to plugin-aws-inven-collector.)
=> Move to collector to plugin-aws-inven-collector.

src/spaceone/inventory/connector/aws_iam_connector/connector.py, src/spaceone/inventory/connector/aws_iam_connector/schema/data.py, src/spaceone/inventory/connector/aws_lambda_connector/connector.py, src/spaceone/inventory/connector/aws_lambda_connector/schema/data.py, src/spaceone/inventory/connector/aws_lambda_connector/schema/resource.py, src/spaceone/inventory/connector/aws_lambda_connector/schema/service_type.py
feat: Add iam access_key_age_status. Add lambda package type.
=> Add iam access_key_age_status. Add lambda package type.

src/spaceone/inventory/connector/aws_elb_connector/schema/data.py
fix: Change stats type StringType to IntType.
=> Change stats type StringType to IntType.

src/spaceone/inventory/info/collector_info.py
- refactor: change metadata format of cloud service
=> refactor: change metadata format of cloud service

src/spaceone/inventory/connector/aws_acm_connector/connector.py
fix: Add Includes.keyTypes for getting all algorithms certificates.
=> Add Includes.keyTypes for getting all algorithms certificates.

src/spaceone/inventory/connector/aws_iam_connector/connector.py
fix: Change age status value to range days.
=> Change age status value to range days.

src/spaceone/inventory/connector/aws_iam_connector/connector.py
fix: Change no access key age status display name.
=> Change no access key age status display name.

README.md, src/spaceone/inventory/connector/aws_vpc_connector/connector.py
fix: Add vpc route table targets. (Transit GW, Nat GW, Peering Connection)
=> Improvement: Add vpc route table targets. (Transit GW, Nat GW, Peering Connection)

src/spaceone/inventory/connector/aws_vpc_connector/schema/resource.py
fix: Change VPC Routes destination text field.
=> fix: Change VPC Routes destination text field.

src/spaceone/inventory/connector/aws_elb_connector/schema/service_type.py, src/spaceone/inventory/connector/aws_lambda_connector/schema/service_type.py
fix: cloud service list bugs. (ELB, Lambda)
=> fix: cloud service list bugs. (ELB, Lambda)

src/spaceone/inventory/connector/aws_elb_connector/schema/resource.py
fix: Remove duplicate filed. (ELB > Load Balancer > Security Groups)
=> fix: Remove duplicate filed. (ELB > Load Balancer > Security Groups)

src/spaceone/inventory/connector/aws_s3_connector/connector.py, src/spaceone/inventory/connector/aws_s3_connector/schema/data.py, src/spaceone/inventory/connector/aws_s3_connector/schema/service_type.py
feat: Add S3 lifecycle rules.
fix: Change List field object without sub_key.
=> feat: Add S3 lifecycle rules.

src/spaceone/inventory/connector/aws_s3_connector/schema/resource.py
feat: Add new layout for S3 lifecycle.
=> feat: Add new layout for S3 lifecycle.

src/spaceone/inventory/connector/aws_s3_connector/schema/resource.py
refactor: Add more fields for S3 Lifecycle. (Transition, Noncurrent Version Transition)
=> refactor: Add more fields for S3 Lifecycle. (Transition, Noncurrent Version Transition)

src/spaceone/inventory/connector/aws_s3_connector/connector.py, src/spaceone/inventory/connector/aws_s3_connector/schema/data.py, src/spaceone/inventory/connector/aws_s3_connector/schema/service_type.py
refactor: Change S3 Bucket lifecycle rules column name from counts to ids.
=> refactor: Change S3 Bucket lifecycle rules column name from counts to ids.

src/spaceone/inventory/connector/aws_s3_connector/schema/data.py
fix: Remove S3 lifecycle default list data.
=> fix: Remove S3 lifecycle default list data.

src/spaceone/inventory/connector/aws_iam_connector/schema/service_type.py, src/spaceone/inventory/connector/aws_vpc_connector/schema/service_type.py
=> fix: bugs from latest version 

src/spaceone/inventory/connector/aws_ec2_connector/connector.py, src/spaceone/inventory/connector/aws_vpc_connector/schema/resource.py, src/spaceone/inventory/connector/aws_vpc_connector/schema/service_type.py
fix: fix data format & ports setting
=> fix: fix data format & ports setting

src/spaceone/inventory/connector/aws_ec2_connector/schema/data.py
=> fix: fix ports setting

src/spaceone/inventory/conf/cloud_service_conf.py, src/spaceone/inventory/connector/aws_ec2_connector/connector.py, src/spaceone/inventory/connector/aws_ec2_connector/schema/data.py
fix: fix ports setting & Activate EC2 Collect
=> fix: fix ports setting & EC2 Collect Activate

src/spaceone/inventory/conf/cloud_service_conf.py, src/spaceone/inventory/manager/__init__.py
=> fix: fix EC2 Collect Activate

src/spaceone/inventory/connector/aws_ec2_connector/connector.py
fix: fix vulnerable ports logic
=> fix: fix vulnerable ports logic

src/spaceone/inventory/conf/cloud_service_conf.py, src/spaceone/inventory/connector/__init__.py, src/spaceone/inventory/manager/__init__.py
=> fix: fix remove ec2 collect

src/spaceone/inventory/service/collector_service.py
=> fix: fix option bug

src/spaceone/inventory/connector/aws_ec2_connector/connector.py, src/spaceone/inventory/service/collector_service.py
fix: delete vulnerable_ports logic
=> fix: delete vulnerable_ports logic

src/spaceone/inventory/connector/aws_sqs_connector/connector.py
fix: fix sqs connector Queue -> RedrivePolicy key error
=> fix sqs connector Queue -> RedrivePolicy key error

src/spaceone/inventory/conf/cloud_service_conf.py, src/spaceone/inventory/connector/aws_cloud_watch_connector/README.md, src/spaceone/inventory/connector/aws_cloud_watch_connector/__init__.py, src/spaceone/inventory/connector/aws_cloud_watch_connector/connector.py, src/spaceone/inventory/connector/aws_elb_connector/connector.py, src/spaceone/inventory/connector/aws_elb_connector/schema/data.py, src/spaceone/inventory/connector/aws_elb_connector/schema/resource.py, src/spaceone/inventory/connector/aws_sqs_connector/connector.py, src/spaceone/inventory/manager/cloudwatch_manager.py
add Target Health From Target Group
=> fix: add Target Health From Target Group

src/spaceone/inventory/connector/aws_elb_connector/schema/resource.py
=> fix: change Target Health Layout

src/spaceone/inventory/connector/aws_cloud_watch_connector/connector.py
=> fix: fix useless import

src/spaceone/inventory/connector/aws_cloud_watch_connector/README.md, src/spaceone/inventory/connector/aws_cloud_watch_connector/schema/service_type.py
=> fix: fix cloud service setting

src/spaceone/inventory/connector/aws_cloud_watch_connector/schema/data.py, src/spaceone/inventory/connector/aws_cloud_watch_connector/schema/service_type.py
=> fix: delete useless import

src/spaceone/inventory/connector/aws_cloud_watch_connector/connector.py, src/spaceone/inventory/connector/aws_cloud_watch_connector/schema/service_type.py, src/spaceone/inventory/connector/aws_elb_connector/connector.py, src/spaceone/inventory/connector/aws_elb_connector/schema/data.py, src/spaceone/inventory/connector/aws_elb_connector/schema/resource.py, src/spaceone/inventory/connector/aws_elb_connector/schema/service_type.py
add port_display
fix state field & make search limit
=> fix state field & make search limit

src/spaceone/inventory/connector/aws_elb_connector/connector.py, src/spaceone/inventory/connector/aws_elb_connector/schema/data.py
=> fix: fix display port

src/spaceone/inventory/connector/aws_cloud_watch_connector/connector.py, src/spaceone/inventory/connector/aws_cloud_watch_connector/schema/data.py, src/spaceone/inventory/connector/aws_cloud_watch_connector/schema/resource.py, src/spaceone/inventory/connector/aws_cloud_watch_connector/schema/service_type.py
add alarm actions fields & search fields
=> fix: add alarm actions fields & search fields

src/spaceone/inventory/connector/aws_cloud_watch_connector/connector.py
fix cloud watch alarms key error
=> fix: fix cloud watch alarms key error

src/spaceone/inventory/connector/aws_route53_connector/schema/service_type.py, src/spaceone/inventory/service/collector_service.py
add route53 search & rollback init regions logic
=> fix: add route53 search & rollback init regions logic

src/spaceone/inventory/connector/aws_route53_connector/schema/service_type.py
=> fix: add route53 search

src/spaceone/inventory/connector/aws_sqs_connector/connector.py
* fix SQS Queue Data Field Error
=> fix: fix SQS Queue Data Field Error

src/spaceone/inventory/conf/cloud_service_conf.py
=> fix: add regions info

src/spaceone/inventory/connector/aws_documentdb_connector/connector.py
* fix docDB describe_db_clusters filter logic
=> fix: fix docDB describe_db_clusters filter logic

src/spaceone/inventory/connector/aws_elb_connector/connector.py, src/spaceone/inventory/connector/aws_elb_connector/schema/data.py, src/spaceone/inventory/connector/aws_elb_connector/schema/resource.py
* add ELB>LoadBalancer>Listener Rules
=> fix: add ELB>LoadBalancer>Listener Rules

src/spaceone/inventory/connector/aws_elb_connector/connector.py, src/spaceone/inventory/connector/aws_elb_connector/schema/resource.py
* fix ELB listener_rule action_type
=> fix: fix ELB listener_rule action_type

src/spaceone/inventory/connector/aws_elb_connector/connector.py
* fix listener rule data process
=> fix: fix listener rule data process

src/spaceone/inventory/connector/aws_elb_connector/connector.py
* fix describe listener rule join error
=> fix: fix describe listener rule join error

src/spaceone/inventory/connector/aws_elb_connector/connector.py
* fix listener rules NoneType error
=> fix: listener rules NoneType error

src/spaceone/inventory/connector/aws_elb_connector/connector.py
* fix listener rules conditions formatting
=> fix: fix listener rules conditions formatting

README.md
=> add: 수집 설정 가이드 READEME 추가

README.md, src/spaceone/inventory/connector/aws_documentdb_connector/connector.py
* docdb describe_db_clusters filter 원복 (docdb정보만 필요)
=> add: docdb describe_db_clusters filter 원복 (docdb정보만 필요)

src/spaceone/inventory/connector/aws_route53_connector/connector.py
Route53 RecordSet 정보에서 type A일경우 일부 데이터에서 Value가 없는 이슈 => 처리 다양성 개선
=> add: Route53 RecordSet 정보에서 type A일경우 일부 데이터에서 Value가 없는 이슈 => 처리 다양성 개선

src/spaceone/inventory/connector/aws_kms_connector/connector.py
* KMS Alias Cross Check 시에 정상적으로 처리가 안되는 이슈 (iterator issue)
=> add: KMS Alias Cross Check 시에 정상적으로 처리가 안되는 이슈 (iterator issue)
